defaultProject: mde-pso-data-wranglers
defaultLocation: us-central1
defaultDataset: imdb_final
defaultAssertionDataset: imdb_assertions
dataformCoreVersion: 3.0.0-beta.4
vars:
    LOAD_GCS_BUCKET: dataform-imdb-demo/imdb
    RAW_DATA: imdb_staging
    TARGET_DATA: imdb_final
    CONTROL_TABLE: BQEDWControlTable